DROP DATABASE IF EXISTS tagarela;

CREATE DATABASE tagarela;

USE tagarela;


CREATE TABLE USERS(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(50) NOT NULL UNIQUE,
    PASSWORD VARCHAR(40) NOT NULL
);

INSERT INTO USERS VALUES (1, 'admin1', SHA1('senha'));
INSERT INTO USERS VALUES (2, 'admin2', SHA1('senha'));
INSERT INTO USERS VALUES (3, 'user1', SHA1('senha'));
INSERT INTO USERS VALUES (4, 'user2', SHA1('senha'));
